version: '3.4'
services:
  mariadb:
    image: mysql:8.0 # mariadb:11.5.2
    ports:
      - "13306:3306"
    command:
      --init-file /data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bicycle
      MYSQL_USER: javafxTest
      MYSQL_PASSWORD: changeme
    volumes:
      - C:/mariadb:/var/lib/mysql
      - C:/Users/Bird/Desktop/4 курс/уп джава/project/database/init.sql:/data/application/init.sql

#    network_mode: "host"
